### ISSUE TITLE
Login and OTP Screen scroll

### ISSUE THREAD

**Issue by vinayakmalviya** [vinayakmalviya/Teledermatology#4]
Login and OTP Screens have scrolling enabled regardless of the content on screen. It could be a margin or flex irregularity. Issue persists on all android devices tested. iOS devices not tested yet.

Steps to reproduce:
1. `cd <repo>`
2. `react-native start`
For android:
3. `react-native run-android`
For iOS:
3. `react-native run-ios`
4. Try scrolling on the first page

Screenshots:
Android
Login Screen
Initial | After Scroll
------------ | -------------
![Login 1](https://user-images.githubusercontent.com/42168249/83158582-92148600-a122-11ea-82b1-0cec8596f2b1.jpg) | ![Login 2](https://user-images.githubusercontent.com/42168249/83158661-ab1d3700-a122-11ea-8120-08c583bab0bb.jpg)

OTP Screen:
Initial | After Scroll
------------ | -------------
![OTP 2](https://user-images.githubusercontent.com/42168249/83159259-6645d000-a123-11ea-8360-47ea96fbffc2.jpg) | ![OTP 1](https://user-images.githubusercontent.com/42168249/83159284-6e057480-a123-11ea-88ea-9b3089534e3c.jpg)

iOS
Login Screen:
Initial | After Scroll
------------ | -------------
![Simulator Screen Shot - iPhone 11 - 2020-05-28 at 22 27 46](https://user-images.githubusercontent.com/42168249/83172743-aca42a80-a135-11ea-8ed2-cf873e4348f1.png) | ![Simulator Screen Shot - iPhone 11 - 2020-05-28 at 22 27 38](https://user-images.githubusercontent.com/42168249/83172786-bc237380-a135-11ea-8a86-9fedd50cf333.png)

OTP Screen:
Initial | After Scroll
------------ | -------------
![Simulator Screen Shot - iPhone 11 - 2020-05-28 at 22 45 27](https://user-images.githubusercontent.com/42168249/83172942-f42ab680-a135-11ea-84b2-d9dccafe490c.png) | ![Simulator Screen Shot - iPhone 11 - 2020-05-28 at 22 45 31](https://user-images.githubusercontent.com/42168249/83173016-099fe080-a136-11ea-9566-6f2ffb679fce.png)

**Comment by dvjn** [comment]
@vinayakm4261, seems like only notched phones are experiencing this bug.

**Comment by vinayakmalviya** [comment]
@divykj Tested on OnePlus 5 and Huawei Honor 6x - issue persists

**Comment by dvjn** [comment]
Any idea what is the reason for this issue?

**Comment by vinayakmalviya** [comment]
Height assigned to ScrollView in ScreenWrapper could be it:

```javascript
const { height } = useScreenDimensions();
<ScrollView
        contentContainerStyle={{
        height: height - StatusBar.currentHeight,
}}>
```

I guess `flexGrow: 1` instead of `height` would solve it

```javascript
<ScrollView
        contentContainerStyle={{
        flexGrow: 1,
}}>
```

**Comment by dvjn** [comment]
> I guess `flexGrow: 1` instead of `height` would solve it

Doesn't work, leaves extra space below.
![20200528_235016](https://user-images.githubusercontent.com/62170586/83178369-0c9ecf00-a13e-11ea-9c6c-ec624bd280cf.jpg)

**Comment by vinayakmalviya** [comment]
@divykj Try adding `flexGrow: 1` in the style prop of ScrollView not in contentContainerStyle

**Comment by dvjn** [comment]
Still doesn't work :cry:

**Comment by dvjn** [comment]
Try this.

**Comment by vinayakmalviya** [comment]
Good job. It's fixed. Tested on Android as well as iOS

@divykj
