### ISSUE TITLE
[iOS] DateTimePicker and Picker not rendering properly

### ISSUE THREAD

**Issue by vinayakmalviya** [vinayakmalviya/Teledermatology#8]
Picker initially renders behind the TextInput and comes to focus after DateTimePicker is selected. DateTimePicker does not render at all. Cannot submit the form as no date and gender are selected.

Steps to reproduce:

1. `cd <repo>`
2. `react-native start`
3. `react-native run-ios`

Screenshots:

Initial Screen | After DateTimePicker is pressed
------------ | ------------
![Simulator Screen Shot - iPhone 11 - 2020-06-06 at 22 03 09](https://user-images.githubusercontent.com/42168249/83976413-5abe8a00-a917-11ea-9c6b-f21764cd735d.png) | ![Simulator Screen Shot - iPhone 11 - 2020-06-06 at 22 03 28](https://user-images.githubusercontent.com/42168249/83976420-60b46b00-a917-11ea-95cb-95e1288fac43.png)

**Comment by dvjn** [comment]
@vinayakm4261 
Try this for DateTimePicker bug.

**Comment by vinayakmalviya** [comment]
@divykj
Yep, the DateTimePicker works perfectly now

Before | After
------------ | ------------
!![Simulator Screen Shot - iPhone 11 - 2020-06-06 at 22 03 28](https://user-images.githubusercontent.com/42168249/83976420-60b46b00-a917-11ea-95cb-95e1288fac43.png) | ![Simulator Screen Shot - iPhone 11 - 2020-06-08 at 17 32 30](https://user-images.githubusercontent.com/42168249/84045606-a1b78880-a9c6-11ea-8192-5f64de631e6f.png)

**Comment by dvjn** [comment]
@vinayakm4261 
This should solve it.

**Comment by vinayakmalviya** [comment]
@divykj 
Yup, it works. Good job.
